### ISSUE TITLE
Unable to start from repo

### ISSUE THREAD

**Issue by gusarov** [cruizba/ubuntu-dind#1]
Hello,  the cruizba/ubuntu-dind works, but when I'm trying to build the same from this repo it is not actually starting

docker build -t dind .
docker run --privileged -it --rm -v /var/run/docker.sock:/var/run/docker.sock --name dind dind

standard_init_linux.go:211: exec user process caused "no such file or directory"

The reason why I'm researching this, is because I also need dind on ubuntu but I need 18.04 version because Azure Dev Ops pipeline works with 18.04 and I want to have a docker in dockerized Azure Dev Ops  agent

**Comment by cruizba** [comment]
Hi @gusarov did you try to run it without `-v /var/run/docker.sock:/var/run/docker.sock`?. You don't need to share docker unix socket from host.

**Comment by gusarov** [comment]
Hi, @cruizba, yep, I've tried that as well - same issue.

**Comment by cruizba** [comment]
I'll take I look when I have a little bit of time. I'll also try to automate the buildings with github actions and I will do a new docker releases format:

```
cruizba/ubuntu-dind:<ubuntu-version>-<docker-version>
```

If you find some solution, you're free to do a pull request :)

Regards,
Carlos
