### ISSUE TITLE
Fonts and Terminal

### ISSUE THREAD

**Issue by StevenXL** [cruizba/ubuntu-dind#29]
Hi. Thank you very much for your work. 

I am wondering if you could help me out. My workflow is:

1. I SSH into my VPS
2. From my VPS I run `docker container exec --interactive --tty <ubuntu-didn-container-id> /bin/bash`
3. Once I am in my dind container, I attach tmux `tmux attach`
4. I open my LazyVim editor

Unfortunately, the icons are not rendering properly. This is what it looks like when I follow the workflow above:

![image](https://github.com/cruizba/ubuntu-dind/assets/7391433/736ca93a-485c-47b1-869f-920584f5db06)

It should look like this:

![image](https://github.com/cruizba/ubuntu-dind/assets/7391433/4548e4fc-993b-4cde-ae34-f2d5f686ec7e)

I am wondering what I need to do to fix this issue.

**Comment by cruizba** [comment]
Take a look to this: https://unix.stackexchange.com/a/189178 , I think it is related.
