### ISSUE TITLE
POD is restarting continuously to connect dockerd

### ISSUE THREAD

**Issue by GopikaV24** [cruizba/ubuntu-dind#5]
I am trying to use this image in AKS POD  to connect GitHub self-hosted agent. But POD is restarting continuously. After >50 restarts Dockerd connects successfully.

POD Logs: 
```yaml
[Thu Jan  6 06:25:26 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waited 27 seconds of 30 seconds
[Thu Jan  6 06:25:27 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
[Thu Jan  6 06:25:27 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waited 28 seconds of 30 seconds
[Thu Jan  6 06:25:28 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Process dockerd is not running yet. Retrying in 1 seconds
[Thu Jan  6 06:25:28 UTC 2022] [INFO] [/usr/local/bin/startup.sh] Waited 29 seconds of 30 seconds
[Thu Jan  6 06:25:29 UTC 2022] [ERROR]  dockerd is not running after max time
```

Can you please help us on this?

**Comment by ghost** [comment]
I have the same situation.

**Comment by cruizba** [comment]
I've never tested this image in a kubernetes cluster. Take into account that some k8s cluster may not be able to run privileged containers.

This is an experimental image, I can not fit all use cases, so I will close this issue.
