### ISSUE TITLE
Update docker-compose

### ISSUE THREAD

**Issue by svanharmelen** [cruizba/ubuntu-dind#9]
Hi @cruizba! We stubled upon this repo and it solved a problem we had. So thank you for making and sharing this repo!

Yet we do have one little thingy which requires us to fork the repo, and that is that we need this for arm64. This should all work fine, except that docker-compose doesn't have prebuild releases for arm64 for their 1.x versions.

So is it possible to switch to a 2.x version for compose? Or would it be possible to make it configurable? If not, we'll just keep using our fork, but I generally prefer to try and "fix" (of course it's not really broken atm) things upstream whenever possible 😊

**Comment by cruizba** [comment]
Hi @svanharmelen , I do not have too much time right now but, if you want to create a PR with the new docker compose version, I would merge without any problem :)

**Comment by svanharmelen** [comment]
Thanks @cruizba! Created PR #10 to update to the latest docker-compose 👍🏻

**Comment by cruizba** [comment]
I'll take a look this weekend. Is it possible to install docker-compose as a binary? I thought it was a plugin of docker.

Now I am asking myself if someone may want to execute `docker compose` instead of `docker-compose` :thinking:

**Comment by svanharmelen** [comment]
Not sure... We don't even use docker-compose at all, but we need this change so we can build the container for arm64 😅

**Comment by svanharmelen** [comment]
Any updates/thoughts on this one?

**Comment by cruizba** [comment]
Done, I've added a symlink to docker compose plugins, so the command `docker compose` and `docker-compose` can be used.

https://github.com/cruizba/ubuntu-dind/commit/720ed822b9c27ada883272668ee38ba0eb70718e

**Comment by svanharmelen** [comment]
Super nice, thanks!
